### PR TITLE
simplelru: add simple LRU implementation with TTL

### PR DESCRIPTION
**Pull request by amery**

### CODE REVIEW

**Comment by amery** [comment]
amended as I had forgotten to increment/decrement the item count @karasz

**Review by karasz — CHANGES_REQUESTED** [review]
I would think that EvictExpired should be a function that does not return, suitable for a wg.Go() call and run in the background continuously

**Comment by amery** [comment]
> I would think that EvictExpired should be a function that does not return, suitable for a wg.Go() call and run in the background continuously 

My reasoning behind making EvictExpired an event is locking. simplelru doesn't have an internal lock so thread-safety an internal periodic worker could damage it if not coordinated with the higher layer.

There are eviction mechanisms in Add and Get, but a worker around EvictExpired needs to coordinate with whoever calls Add and Get and also prevent stampedes.

**Comment by amery** [comment]
this _simplelru_ was made while trying (and failing) to implement a safe memcache with the cache.Cache interface

**Comment by amery** [comment]
`ForEach` also implements _semi-automatic_ eviction

**Review by karasz — APPROVED** [review]
ok

**Comment by amery** [comment]
`x/simplelru/v0.0.1` tagged

**Pull request merged**
