### PR TITLE
memcache: add thread-safe []byte LRU built on top of our simplelru

### PR DESCRIPTION
**Pull request by amery**
a proper cache.Cache implementation will follow soon, named Memcache.

### CODE REVIEW

**Comment by amery** [comment]
amended so Add receives a time.Time as everything else in this package

**Comment by amery** [comment]
amended for changes to `simplelru` on #10

**Comment by amery** [comment]
rebased and `go.mod` updated to use `cache/x/simplelru@v0.0.2` @karasz

**Comment by amery** [comment]
> It would be nice if you could add a callback to the Add function similar to the evict one. It might prove useful from an instrumenting point of view.

on memcache.LRU or also simplelru.LRU? @karasz

**Review by karasz — APPROVED** [review]
looks ok, only actually using will reveal other needs

**Comment by amery** [comment]
`x/memcache/v0.0.1` tagged

**Pull request merged**
